In [1]:
import pandas as pd
df = pd.read_csv(r'/Users/arup/Documents/sorter-clubbing-optimizer/origin_destination_flow.csv')

df

/var/folders/lw/mxt4vf712k5_lslhrjcqqj700000gn/T/ipykernel_53329/1517739348.py:2: DtypeWarning: Columns (0,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,545,546,547,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,578,580,581,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,656,657,658,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,682,683,684,685,686,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,738,739,740,741,743,744,745,746,747,748,749,750,752,753,754,755,756,757,758,759,762,763,764,765,767,768,769,771,772,773,774,775,776,777,778,779,780,781,782,783,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,802,805,806,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,862,863,864,865,867,869,870,871,872,873,874,875,876,878,879,880,883,884,885,886,887,889,890,891,892,893,894,895,896,897,898,899,900,902,903,904,905,907,908,910,912,913,914,915,916,917,918,919,920,921,922,923,924,926,928,929,930,932,933,934,935,939,941,942,943,944,945,946,947,949,950,951,952,953,954,955,956,958,960,961,962,963,965,966,967,968,969,971,972,974,976,977,978,979,980,981,982,983,984,985,986,987,989,990,991,992,993,994,995,996,997,998,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1026,1027,1028,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1047,1048,1049,1050,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'/Users/arup/Documents/sorter-clubbing-optimizer/origin_destination_flow.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1059,Unnamed: 1060,Unnamed: 1061,Unnamed: 1062,Unnamed: 1063,Unnamed: 1064,Unnamed: 1065,Unnamed: 1066,Unnamed: 1067,Unnamed: 1068
0,NaN,NaN,NaN,NaN,NaN,Volume,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,East,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,BBI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,ANGUL,BALASORE,BERHAMPUR -OR,NaN,BHADRAK,...,NaN,NaN,RATNAGIRI,SANGLI,SATARA,NaN,SHIRDI,SHIRWAL,SOLAPUR,TEMBHURNI
4,NaN,NaN,NaN,NaN,NaN,W09-ANGUL BRANCH,W06-BALASORE BRANCH,W04-BERHAMPUR BRANCH,W54-KHALLIKOTE BRANCH,W14-BHADRAK SORTING OFFICE,...,P65-RANJANGAON BRANCH,P73-TALEGAON BRANCH,P60-RATNAGIRI BRANCH,P10-SANGLI SUPER FRANCHISEE,P13-SATARA SUPER FRANCHISEE,P32-KARAD SORTING OFFICE,P71-SHIRDI-NODAL POINT,P57-SHIRWAL BRANCH,P06-SOLAPUR BRANCH,P28-TEMBHURNI SORTING OFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2471,NaN,NaN,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2472,NaN,NaN,NaN,NaN,BS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2473,NaN,NaN,NaN,NaN,EP,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2474,NaN,NaN,NaN,NaN,ES,NaN,NaN,NaN,NaN,NaN,...,2,3,3.0,11.0,10.0,8.0,1.0,2,36,1
2475,NaN,NaN,NaN,NaN,GP,NaN,NaN,NaN,NaN,NaN,...,4,NaN,NaN,3.0,NaN,NaN,2.0,NaN,11,NaN

In [2]:
# For the first 4 columns, fill down the last seen non-null value from row index 5 onwards
cols_to_fill = df.columns[:4]
for col in cols_to_fill:
    df.loc[5:, col] = df.loc[5:, col].ffill()

df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1059,Unnamed: 1060,Unnamed: 1061,Unnamed: 1062,Unnamed: 1063,Unnamed: 1064,Unnamed: 1065,Unnamed: 1066,Unnamed: 1067,Unnamed: 1068
0,NaN,NaN,NaN,NaN,NaN,Volume,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,East,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,BBI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,ANGUL,BALASORE,BERHAMPUR -OR,NaN,BHADRAK,...,NaN,NaN,RATNAGIRI,SANGLI,SATARA,NaN,SHIRDI,SHIRWAL,SOLAPUR,TEMBHURNI
4,NaN,NaN,NaN,NaN,NaN,W09-ANGUL BRANCH,W06-BALASORE BRANCH,W04-BERHAMPUR BRANCH,W54-KHALLIKOTE BRANCH,W14-BHADRAK SORTING OFFICE,...,P65-RANJANGAON BRANCH,P73-TALEGAON BRANCH,P60-RATNAGIRI BRANCH,P10-SANGLI SUPER FRANCHISEE,P13-SATARA SUPER FRANCHISEE,P32-KARAD SORTING OFFICE,P71-SHIRDI-NODAL POINT,P57-SHIRWAL BRANCH,P06-SOLAPUR BRANCH,P28-TEMBHURNI SORTING OFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2471,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2472,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2473,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,EP,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2474,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,ES,NaN,NaN,NaN,NaN,NaN,...,2,3,3.0,11.0,10.0,8.0,1.0,2,36,1
2475,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,GP,NaN,NaN,NaN,NaN,NaN,...,4,NaN,NaN,3.0,NaN,NaN,2.0,NaN,11,NaN

In [3]:
# For the first 4 rows, fill right (horizontally) from the 6th column onwards with the last seen non-null value
import numpy as np

start_col = 5  # 0-based index, so 6th column
end_col = df.shape[1]
for row in range(4):
    last_val = np.nan
    for col in range(start_col, end_col):
        if pd.notnull(df.iat[row, col]):
            last_val = df.iat[row, col]
        else:
            df.iat[row, col] = last_val

df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1059,Unnamed: 1060,Unnamed: 1061,Unnamed: 1062,Unnamed: 1063,Unnamed: 1064,Unnamed: 1065,Unnamed: 1066,Unnamed: 1067,Unnamed: 1068
0,NaN,NaN,NaN,NaN,NaN,Volume,Volume,Volume,Volume,Volume,...,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt
1,NaN,NaN,NaN,NaN,NaN,East,East,East,East,East,...,West,West,West,West,West,West,West,West,West,West
2,NaN,NaN,NaN,NaN,NaN,BBI,BBI,BBI,BBI,BBI,...,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ
3,NaN,NaN,NaN,NaN,NaN,ANGUL,BALASORE,BERHAMPUR -OR,BERHAMPUR -OR,BHADRAK,...,PUNE,PUNE,RATNAGIRI,SANGLI,SATARA,SATARA,SHIRDI,SHIRWAL,SOLAPUR,TEMBHURNI
4,NaN,NaN,NaN,NaN,NaN,W09-ANGUL BRANCH,W06-BALASORE BRANCH,W04-BERHAMPUR BRANCH,W54-KHALLIKOTE BRANCH,W14-BHADRAK SORTING OFFICE,...,P65-RANJANGAON BRANCH,P73-TALEGAON BRANCH,P60-RATNAGIRI BRANCH,P10-SANGLI SUPER FRANCHISEE,P13-SATARA SUPER FRANCHISEE,P32-KARAD SORTING OFFICE,P71-SHIRDI-NODAL POINT,P57-SHIRWAL BRANCH,P06-SOLAPUR BRANCH,P28-TEMBHURNI SORTING OFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2471,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2472,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2473,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,EP,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2474,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,ES,NaN,NaN,NaN,NaN,NaN,...,2,3,3.0,11.0,10.0,8.0,1.0,2,36,1
2475,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,GP,NaN,NaN,NaN,NaN,NaN,...,4,NaN,NaN,3.0,NaN,NaN,2.0,NaN,11,NaN

In [4]:
# From 6th row and 6th column (i.e., index 5 onwards), ensure all values are numbers, fix numbers written as text with commas, and fill missing values with 0

# Select the sub-DataFrame to process
numeric_block = df.iloc[5:, 5:]

# Remove commas and convert to numeric, coerce errors to NaN
numeric_block = numeric_block.applymap(lambda x: pd.to_numeric(str(x).replace(',', ''), errors='coerce'))

# Fill missing values with 0
numeric_block = numeric_block.fillna(0)

# Assign back to the original DataFrame
df.iloc[5:, 5:] = numeric_block

df

/var/folders/lw/mxt4vf712k5_lslhrjcqqj700000gn/T/ipykernel_53329/4203184249.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  numeric_block = numeric_block.applymap(lambda x: pd.to_numeric(str(x).replace(',', ''), errors='coerce'))

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1059,Unnamed: 1060,Unnamed: 1061,Unnamed: 1062,Unnamed: 1063,Unnamed: 1064,Unnamed: 1065,Unnamed: 1066,Unnamed: 1067,Unnamed: 1068
0,NaN,NaN,NaN,NaN,NaN,Volume,Volume,Volume,Volume,Volume,...,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt,Billed Wt
1,NaN,NaN,NaN,NaN,NaN,East,East,East,East,East,...,West,West,West,West,West,West,West,West,West,West
2,NaN,NaN,NaN,NaN,NaN,BBI,BBI,BBI,BBI,BBI,...,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ,PNQ
3,NaN,NaN,NaN,NaN,NaN,ANGUL,BALASORE,BERHAMPUR -OR,BERHAMPUR -OR,BHADRAK,...,PUNE,PUNE,RATNAGIRI,SANGLI,SATARA,SATARA,SHIRDI,SHIRWAL,SOLAPUR,TEMBHURNI
4,NaN,NaN,NaN,NaN,NaN,W09-ANGUL BRANCH,W06-BALASORE BRANCH,W04-BERHAMPUR BRANCH,W54-KHALLIKOTE BRANCH,W14-BHADRAK SORTING OFFICE,...,P65-RANJANGAON BRANCH,P73-TALEGAON BRANCH,P60-RATNAGIRI BRANCH,P10-SANGLI SUPER FRANCHISEE,P13-SATARA SUPER FRANCHISEE,P32-KARAD SORTING OFFICE,P71-SHIRDI-NODAL POINT,P57-SHIRWAL BRANCH,P06-SOLAPUR BRANCH,P28-TEMBHURNI SORTING OFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2471,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BP,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2472,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,BS,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2473,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,EP,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2474,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,ES,0.0,0.0,0.0,0.0,0.0,...,2.0,3.0,3.0,11.0,10.0,8.0,1.0,2.0,36.0,1.0
2475,West,PNQ,TEMBHURNI,P28-TEMBHURNI SORTING OFFICE,GP,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,11.0,0.0

In [5]:
df.to_csv('data.csv', index=False)

In [1]:
import pandas as pd
from algorithms import filter_and_sum

def summarize_by_branch_type_mode(csv_path="data.csv"):
    df = pd.read_csv(csv_path, header=None, low_memory=False)
    branches = df.iloc[6:, 3].unique()

    types = ["Volume", "Billed Wt"]
    modes = ["Air", "Ground"]

    records = []
    for branch in branches:
        for mode in modes:
            for type_ in types:
                total = filter_and_sum(
                    type_=type_,
                    mode=mode,
                    org_branch=branch,
                    csv_path=csv_path
                )
                records.append({
                    "org_branch": branch,
                    "type": type_,
                    "mode": mode,
                    "sum": total
                })

    return pd.DataFrame(records)

# Run the summarizer
branch = summarize_by_branch_type_mode("data.csv")

# (Optional) Save to CSV if you want a file
branch.to_csv("branch_summary.csv", index=False)

# Check first few rows
branch

                        org_branch       type    mode      sum
0                 W09-ANGUL BRANCH     Volume     Air    416.0
1                 W09-ANGUL BRANCH  Billed Wt     Air    195.0
2                 W09-ANGUL BRANCH     Volume  Ground   5069.0
3                 W09-ANGUL BRANCH  Billed Wt  Ground  10210.0
4              W06-BALASORE BRANCH     Volume     Air    596.0
...                            ...        ...     ...      ...
2147            P06-SOLAPUR BRANCH  Billed Wt  Ground  12949.0
2148  P28-TEMBHURNI SORTING OFFICE     Volume     Air     52.0
2149  P28-TEMBHURNI SORTING OFFICE  Billed Wt     Air     32.0
2150  P28-TEMBHURNI SORTING OFFICE     Volume  Ground   2269.0
2151  P28-TEMBHURNI SORTING OFFICE  Billed Wt  Ground   1309.0

[2152 rows x 4 columns]